version: '3.4'

services:
  daprclienttest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6002:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  daprservertest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5016
    ports:
      - "5003:5016"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
